name: Tests and Codacy Coverage

on:
  push:
    branches:
      - main
      - master
      - develop
      - fix/**
      - feat/**
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage (XML, HTML)
        run: |
          pytest tests/unit/ --cov=src --cov-report=term-missing --cov-report=xml --cov-report=html -v

      - name: Upload coverage to Codacy
        if: ${{ env.CODACY_API_TOKEN != '' }}
        env:
          CODACY_ORGANIZATION_PROVIDER: gh
          CODACY_USERNAME: Mosfet04
          CODACY_PROJECT_NAME: orquestradorIAPythonArgo
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh)

      - name: Upload HTML coverage as artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov/
